### PR TITLE
feat: load details on click.

### PR DESCRIPTION
**Pull request by thorwebdev**
Load additional details from database on click:
image

loaded
image

### CODE REVIEW

**Comment by bdon** [comment]
I'm getting a 406 error for the details view, did you download the data using `overturemaps` before 5/16? the dataset schema may have evolved since the May 16 release

**Comment by thorwebdev** [comment]
Oh I downloaded most certainly after 5/16, hmm, sorry. Is there a way to run a specific version to make sure folks don't run into this?

**Comment by thorwebdev** [comment]
Ah, no @bdon the problem is that your function doesn't expose the id. Can you go and run the function creation from here? https://github.com/bdon/supabase-vector-tile/blob/main/function.sql

**Comment by bdon** [comment]
@thorwebdev got it, I missed that!

There isn't a way to choose to download a specific version yet: https://github.com/OvertureMaps/overturemaps-py/issues/17

**Pull request merged**
